### ISSUE TITLE
Try to fix issues related to exe files

### ISSUE THREAD

**Issue by kvendingoldo** [tofuutils/tenv#106]
Chocolatey can't approve package that does not pass security checks. At our exe files we can see the following issues:
https://www.virustotal.com/gui/file/687eae6e12c80e66da0a2b7afe1db14ff2ed6bb184302dd99b8281d8798dccd2/detection/f-687eae6e12c80e66da0a2b7afe1db14ff2ed6bb184302dd99b8281d8798dccd2-1712610596
https://www.virustotal.com/gui/file/a287e1a249eaaa6d07503aaa0ee8b6ef1070d8544573ce47f0bd1cce476aa116/detection/f-a287e1a249eaaa6d07503aaa0ee8b6ef1070d8544573ce47f0bd1cce476aa116-1712606565

we need to think how to fix or avoid them

**Comment by dvaumoron** [comment]
https://go.dev/doc/faq#virus

**Comment by dvaumoron** [comment]
That's a false positive (no reason to think the GitHub toolchain was corrupted)

However, I don't know what to do about that, any idea ?

**Comment by kvendingoldo** [comment]
Talked with admins of chocolatey, they agreed that it's false positive
