### ISSUE TITLE
Add regex support for version-file

### ISSUE THREAD

**Issue by florianmagnin** [tofuutils/tenv#107]
Hello,

It could be nice to have the same support than tfenv for regex in .terraform-version and even .opentofu-version.

So we can choose specific version, beta or not beta...

```
$ cat .opentofu-version
latest

$ cat .terraform-version 
latest:^1\.[0-9].[0-9]$

$ tfenv install
Terraform v1.8.1 is already installed

$ tenv tf install
Resolved version from .terraform-version : latest:^1\.[0-9].[0-9]$
Error: Malformed constraint: latest:^1\.[0-9].[0-9]$
```

Thanks,
Regards,
Florian

**Comment by dvaumoron** [comment]
Hi,

**tenv** use [go-version](https://github.com/hashicorp/go-version), allowing use of version constraint like ">= 1.0, < 1.4"

Have you a specific requirement that could not be done with version constraint ?

**Comment by florianmagnin** [comment]
Hello,

I didn't understand this by reading the README, thanks!

Then it could be nice because you support tfenv file but not synthax, that's a bit weird :) and make it easier for massive migrations from terraform/tfenv to opentofu/tenv.

**Comment by dvaumoron** [comment]
I added regexp support for compatibility with tfenv, however there is a message displayed upon their use (I think they are more complex than version constraint, so less readable, without different use cases).
