### ISSUE TITLE
Error: searched asset not found

### ISSUE THREAD

**Issue by lambohamp** [tofuutils/tenv#109]
**Describe the bug**
Hi. I am getting the following error when running `tenv tg install latest`:

```
$ tenv tg install latest 
Fetching all releases information from https://api.github.com/repos/gruntwork-io/terragrunt/releases
Found compatible version remotely : 0.57.9
Installing Terragrunt 0.57.9
Fetching release information from https://api.github.com/repos/gruntwork-io/terragrunt/releases/tags/v0.57.9
Error: searched asset not found
Usage:
  tenv tg install [version] [flags]

Flags:
  -a, --arch string           specify arch for binaries downloading (default "arm64")
  -t, --github-token string   GitHub token (increases GitHub REST API rate limits)
  -h, --help                  help for install
  -c, --remote-conf string    path to remote configuration file (advanced settings)
  -u, --remote-url string     remote url to install from

Global Flags:
  -q, --quiet              no unnecessary output (and no log)
  -r, --root-path string   local path to install versions of OpenTofu, Terraform and Terragrunt (default "/Users/dmitriyp/.tenv")
  -v, --verbose            verbose output (and set log level to Trace)

searched asset not found
```

**To Reproduce**
1. Run `tenv tg install latest`
4. See the error

**Expected behavior**
The latest version of Terragrunt is installed.

**Screenshots**
N/A

**Environment:**
- OS: macOS, Ubuntu
- tenv version v1.7.1

**Comment by lambohamp** [comment]
The issue has self-resolved.

**Comment by dvaumoron** [comment]
Hi,

The problem was the GitHub rate limit ?

**Comment by lambohamp** [comment]
Hi, I am not sure, to be honest. It disappeared so quickly that I didn't even start the troubleshooting. 
But since the issue was reproducible on different machines with different GitHub keys, I don't think it was caused by the GitHub rate limit.

**Comment by dvaumoron** [comment]
Seem pretty strange, does not sound like a GitHub rate limit problem indeed, so I have no clue on what could have been wrong. Have you often network issues ?
