### ISSUE TITLE
Terraform 1.8.2+ contains LICENSE.txt file within artefact archive

### ISSUE THREAD

**Issue by kvendingoldo** [tofuutils/tenv#110]
**Is your feature request related to a problem? Please describe.**
The 1.8.2+ version of Terraform contains additional LICENSE.txt file. 

**Describe the solution you'd like**
We should extract only terraform binary file, nothing else.

**Comment by dvaumoron** [comment]
Why was it an issue ? (I don't think many people will want to check LICENSE.txt, however adding complexity to remove them seems unnecessary)

**Comment by kvendingoldo** [comment]
@dvaumoron agree that it's not an issue, but it does not make any sense to post extra files like LICENSE.txt to filesystem. Agree that solution a little bit complicated, we can rethink it in the future.
