### ISSUE TITLE
is it expected that OpenTofu will be installed no matter what?

### ISSUE THREAD

**Issue by corporate-gadfly** [tofuutils/tenv#115]
## Background
* Small-ish terragrunt project (running with terraform 1.8.0/terragrunt 0.57.13)
* Not ready to move to OpenTofu yet

## Problem
* After moving from `tfenv/tgswitch` to `tenv` in Azure DevOps pipeline, I ran into issues, as it felt like some terragrunt/terraform commands were running with `tofu` and some with `terraform`.

## Symptoms
* While running terragrunt command `terragrunt run-all plan`, I saw snippets mentioning OpenTofu:
    ```
    OpenTofu has compared your real infrastructure against your configuration and
    found no differences, so no changes are needed.
    ```
* While running terraform command:
    ```
    for file in $(find . -name '*tfplan')
    do
      directory=$(dirname $file)
      terraform -chdir=$directory show -no-color -json tfplan | jq '.' > $directory/tfplan.json
    done
    ```
    I saw the following output:
    ```
    Error: Couldn't show local plan

    Plan read error: plan file was created by Terraform 1.6.2, but this is 1.8.1;
    plan files cannot be transferred between different Terraform versions
    ```
    where 1.8.1 might have been a binary installed on the pipeline agent VM (and 1.6.2 is the **default** OpenTofu installed by tenv?).

## Remedy
What worked for me to force the usage of `terraform` everywhere was to use a pipeline-level environment variable:
```
TOFUENV_AUTO_INSTALL=false
```

Please advise if the workaround is the recommended solution and/or improve the documentation.

**Comment by dvaumoron** [comment]
In case of conflict with already installed version, the `tenv update-path` command should help resolve the issue.

**Comment by dvaumoron** [comment]
It seems that **terragrunt** behavior has changed : https://github.com/gruntwork-io/terragrunt/releases/tag/v0.57.12 and now call `tofu ` first.

**Comment by dvaumoron** [comment]
Moreover if you use a `.terraform-version` and want the ability to use a `.opentofu-version` instead (when times arise to switch to **opentofu**), our `tf` proxy handle this use case.

**Comment by corporate-gadfly** [comment]
> It seems that **terragrunt** behavior has changed : https://github.com/gruntwork-io/terragrunt/releases/tag/v0.57.12 and now call `tofu` first.

Right. So `terragrunt` looks for `tofu` first and `tenv` obliges by installing it automatically unless I turn it off with `TOFUENV_AUTO_INSTALL=false`?
