### ISSUE TITLE
Brew install is missing binaries

### ISSUE THREAD

**Issue by jasonstitt** [tofuutils/tenv#120]
**Describe the bug**

After installing with brew, the only binary on the path is `tenv`.

**To Reproduce**

```
brew install tenv
tenv tofu use 1.7
tenv tg use 0.58

brew ls -v tenv
# output:
/opt/homebrew/Cellar/tenv/1.10.0/INSTALL_RECEIPT.json
/opt/homebrew/Cellar/tenv/1.10.0/LICENSE
/opt/homebrew/Cellar/tenv/1.10.0/bin/tenv
/opt/homebrew/Cellar/tenv/1.10.0/.brew/tenv.rb
/opt/homebrew/Cellar/tenv/1.10.0/etc/bash_completion.d/tenv
/opt/homebrew/Cellar/tenv/1.10.0/README.md
/opt/homebrew/Cellar/tenv/1.10.0/share/zsh/site-functions/_tenv
/opt/homebrew/Cellar/tenv/1.10.0/share/fish/vendor_completions.d/tenv.fish

tree ~/.tenv
# output:
/Users/<x>/.tenv
├── OpenTofu
│   ├── 1.7.0
│   │   └── tofu
│   └── version
└── Terragrunt
    ├── 0.58.0
    │   └── terragrunt
    └── version

tenv update-path
# output:
/opt/homebrew/bin:<rest-of-my-path>

which tofu
# output:
tofu not found
```

**Expected behavior**
Binaries for tofu, terragrunt, terraform -- I believe these are supposed to be installed aliases in the homebrew bin.

**Environment (please complete the following information):**
- OS: macos 14.0
- tofuenv version 1.10.0

**Comment by caass** [comment]
Running into the same issue here, I don't see anything different in the [formula definition](https://github.com/Homebrew/homebrew-core/commits/5f1509692b434becd1d96046041d1ffe31946d3a/Formula/t/tenv.rb)

**Comment by caass** [comment]
This fixed the issue for me:
```sh
brew uninstall tenv && brew install tofuutils/tap/tenv
```

**Comment by jasonstitt** [comment]
The homebrew-core one is based on a source distro while the tap is downloading prebuilt. I guess this line:
```
    system "go", "build", *std_go_args(ldflags:), "./cmd/tenv"
```
Is what is only outputting the `tenv` binary.

**Comment by jasonstitt** [comment]
When a tap shadows the name of a core formula, brew will prefer core unless the qualified path is used. I found documentation: https://docs.brew.sh/Taps#formula-with-duplicate-names

Therefore when the commands in the README are executed:

```
brew tap tofuutils/tap
brew install tenv
```

It's ignoring the tap.

I believe it's more correct to have either the tap or core formula and not both defined.

As a user, I would prefer core.

**Comment by kvendingoldo** [comment]
It's interesting that somebody added tenv to core. I will take a look to it and will try to add our own formula to core.

**Comment by chenrui333** [comment]
👋 homebrew core maintainer here, IMO, tenv should only install tenv, anything else can be installed separately.

**Comment by kvendingoldo** [comment]
@chenrui333 tf / terraform / tofu / tg are wrappers that made by us in scope of tenv repository, not real tools.

**Comment by chenrui333** [comment]
got you, I am installing all of them now (I was under wrong impression)

**Comment by chenrui333** [comment]
also added bunch of conflicts

![image](https://github.com/tofuutils/tenv/assets/1580956/cfb67ec6-d750-4f76-b535-c5c148666b5a)

**Comment by dvaumoron** [comment]
> I believe it's more correct to have either the tap or core formula and not both defined.
> 
> As a user, I would prefer core.

@kvendingoldo, we should maybe add a `tap_migration.json` in tofutils/homebrew-tap and remove the goreleaser configuration part that trigger the generation of our formula version ?

**Comment by kvendingoldo** [comment]
@dvaumoron yep. I think that we'll do that today.

**Comment by caass** [comment]
So what's the preferred action as an end user? Install from the `tofuutils` tap or the main tap?

**Comment by dvaumoron** [comment]
The tofuutils tap now redirect to homebrew-core
