### ISSUE TITLE
Tenv hangs indefinitely 

### ISSUE THREAD

**Issue by shadycuz** [tofuutils/tenv#121]
**Describe the bug**
When running the following command:
```console
$ tenv tf install latest-allowed
Scan project to find .tf files
Fetching all releases information from https://releases.hashicorp.com/terraform/index.json
Found compatible version remotely : 1.8.2
```
tenv hangs indefinitely

When I trace what is going on:
```console
$ strace -f -e trace=file tenv tf install latest-allowed
...
Found compatible version remotely : 1.8.2
[pid  1847] openat(AT_FDCWD, "/home/ubuntu/.tenv/.lock", O_RDONLY|O_CREAT|O_EXCL|O_CLOEXEC, 0644) = -1 ENOENT (No such file or directory)
[pid  1847] openat(AT_FDCWD, "/home/ubuntu/.tenv/.lock", O_RDONLY|O_CREAT|O_EXCL|O_CLOEXEC, 0644) = -1 ENOENT (No such file or directory)
[pid  1839] openat(AT_FDCWD, "/home/ubuntu/.tenv/.lock", O_RDONLY|O_CREAT|O_EXCL|O_CLOEXEC, 0644) = -1 ENOENT (No such file or directory)
[pid  1842] openat(AT_FDCWD, "/home/ubuntu/.tenv/.lock", O_RDONLY|O_CREAT|O_EXCL|O_CLOEXEC, 0644) = -1 ENOENT (No such file or directory)
[pid  1839] openat(AT_FDCWD, "/home/ubuntu/.tenv/.lock", O_RDONLY|O_CREAT|O_EXCL|O_CLOEXEC, 0644) = -1 ENOENT (No such file or directory)
...
```

It just repeats this line forever.

> [pid  1839] openat(AT_FDCWD, "/home/ubuntu/.tenv/.lock", O_RDONLY|O_CREAT|O_EXCL|O_CLOEXEC, 0644) = -1 ENOENT (No such file or directory)

I checked and the `/home/ubuntu/.tenv` directory does not exist.

**To Reproduce**
I have a [docker file](https://github.com/DontShaveTheYak/terraform-module-template/blob/872dc426c796d0d3d0c6134034a8f7febc760497/.devcontainer/Dockerfile) that will give you a reproducible environment.

I think the issue is with Ubuntu 24.04, but it could also be with docker or devcontainers? 

**Expected behavior**
I expected it to install terraform and then exit ;)

**Screenshots**

**Environment (please complete the following information):**
- OS: DevContainer (docker) Ubuntu 24.04
- tofuenv version [e.g. 0.8.0]

**Additional context**
I'm hungry and this PR adds tenv to my project https://github.com/DontShaveTheYak/terraform-module-template/pull/54 , incase you want a template for your next Terraform module =)

**Comment by dvaumoron** [comment]
I will add a mkdir to ensure tenv root path existence.

**Comment by dvaumoron** [comment]
Moreover the lock is now by install path (i.e. different for each tool).
