### ISSUE TITLE
Leftover `.lock` file hangs commands without a message

### ISSUE THREAD

**Issue by jasonstitt** [tofuutils/tenv#123]
**Describe the bug**

Cancelling an install can leave a `.lock` file behind that causes commands to silently hang.

**To Reproduce**

I ran `terraform` to see if I had a version installed and `tenv` started to automatically install it. Being unfamiliar with the auto-install behavior, I hit ctrl-C. All commands (not just `tenv` but `terragrunt` etc.) then started hanging. After I ran one with `-v` I saw:

```
2024-05-02T10:24:48.545-0500 [INFO]  tenv: can not write .lock file, will retry: error="open /Users/<me>/.tenv/.lock: file exists"
```

**Expected behavior**

Clean up lock files on exit, or have a way of dealing with them in other commands

**Screenshots**

**Environment (please complete the following information):**
- OS: macos
- tofuenv version 1.10.0

**Comment by dvaumoron** [comment]
It is hard to ensure the delete of `.lock` file on cancel.

However we can add `tenv <tool>` subcommand  to remove the lock (which is currently by tool).

**Comment by dvaumoron** [comment]
We can also add a retry limit (configurable by an environment variable with a default).

**Comment by dvaumoron** [comment]
> It is hard to ensure the delete of `.lock` file on cancel.

A SIGINT can be managed, but a SIGKILL will still let the `.lock` file.

**Comment by jasonstitt** [comment]
I would suggest cleanup on SIGINT (with a warning if necessary) and also printing a warning to stderr when running a command with a lockfile present (without `-v`).
