### ISSUE TITLE
How do I configure TF Controller for flux to use tenv?

### ISSUE THREAD

**Issue by csantanapr** [tofuutils/tenv#127]
I was not able to find it in the docs

**Comment by dvaumoron** [comment]
The `tfctl` binary has a flag `--terraform` to change the the location of the `terraform` binary (indicated in [CLI References](https://flux-iac.github.io/tofu-controller/tfctl/#installation)

**Comment by kvendingoldo** [comment]
@csantanapr is it the answer to your question?
