### ISSUE TITLE
Add support of https://get.opentofu.org/tofu/ for getting OpenTofu 

### ISSUE THREAD

**Issue by kvendingoldo** [tofuutils/tenv#141]
We can keep GitHub support, but the best way for now is getting releases from https://get.opentofu.org/tofu. We can keep `defaultTofuGithubURL` for backward compatibility and introduce a new var like `defaultHashicorpURL` for OpenTofu releases.

**Comment by dvaumoron** [comment]
That does not seem complicated (**tenv** already have HTML parsing feature), however that mean two incompatible way to build download URL for OpenTofu binaries, (mean a major version change with [semantic versioning](https://semver.org/)).

**Comment by dvaumoron** [comment]
I checked the url in get.openttofu.org and they link to github.com, so there is nothing todo, those settings should work : 

```
TOFUENV_REMOTE=https://github.com
TOFUENV_INSTALL_MODE=direct
TOFUENV_LIST_MODE=html
TOFUENV_LIST_URL=https://get.opentofu.org/tofu
```

(i did not tested it yet)

**Comment by dvaumoron** [comment]
I checked (again, in **tenv** code this time), a change is needed at https://github.com/tofuutils/tenv/blob/main/versionmanager/retriever/tofu/tofuretriever.go#L123

**Comment by dvaumoron** [comment]
As it link on github.com to download archive, I do not see benefit to change **tenv**.

**Comment by kvendingoldo** [comment]
Agree. Let's keep it here for possible future.
