### ISSUE TITLE
Error: searched asset not found

### ISSUE THREAD

**Issue by elefantes** [tofuutils/tenv#149]
**Describe the bug**
Unable to install requested tools such as terraform or terragrunt (tf,tg).

**To Reproduce**
1. `brew install tenv`
2. `tenv tf install latest` or `tenv tf install 1.8.4`
3. See error

**Expected behavior**
It should install the version requested. 

**Screenshots**

```
❯ tenv tf install 1.8.4
Installing Terraform 1.8.4
Fetching release information from https://releases.hashicorp.com/terraform/1.8.4/index.json
Error: searched asset not found
Usage:
  tenv tf install [version] [flags]

Flags:
  -a, --arch string          specify arch for binaries downloading (default "arm")
  -h, --help                 help for install
  -k, --key-file string      local path to PGP public key file (replace check against remote one)
  -c, --remote-conf string   path to remote configuration file (advanced settings)
  -u, --remote-url string    remote url to install from

Global Flags:
  -q, --quiet              no unnecessary output (and no log)
  -r, --root-path string   local path to install versions of OpenTofu, Terraform and Terragrunt (default "/Users/elefantes/.tenv")
  -v, --verbose            verbose output (and set log level to Trace)

searched asset not found
```

**Environment (please complete the following information):**
- OS: macos sonoma 14.5

**Additional context**
I have no problem downloading the assets via cURL or browser from the URL output by the tool.

**Comment by kvendingoldo** [comment]
Hi, thank you for your reporting. I tried to reproduce it at macos 12.2.1, tenv version (1.10.0, 1.11.6) and installed terraform without any problem. Log for the future investigation:

```
$ tenv tf install 1.8.3
Installing Terraform 1.8.3
Fetching release information from https://releases.hashicorp.com/terraform/1.8.3/index.json
Downloading https://releases.hashicorp.com/terraform/1.8.3/terraform_1.8.3_darwin_amd64.zip
Downloading https://releases.hashicorp.com/terraform/1.8.3/terraform_1.8.3_SHA256SUMS
Downloading https://releases.hashicorp.com/terraform/1.8.3/terraform_1.8.3_SHA256SUMS.sig
Downloading https://www.hashicorp.com/.well-known/pgp-key.txt
Installation of Terraform 1.8.3 successful
```

@elefantes may I ask you to enable debug mode and share logs, pls? It can be made via ` tenv tf install 1.8.3 -v`

**Comment by dvaumoron** [comment]
**tenv** rely on [go standard library](https://pkg.go.dev/runtime@go1.22.3#pkg-constants). Adding a debug log to list searched asset will allow a better understanding of the cause of the problem.

**Comment by dvaumoron** [comment]
@elefantes, I added the aforementioned logs, please share your logs again (`tenv tf install 1.8.3 -v`), with 2.0.3, we will see which assets are searched by **tenv**.
