### ISSUE TITLE
Setup docker build

### ISSUE THREAD

**Issue by kvendingoldo** [tofuutils/tenv#15]
At this moment we have Dockerfile, but we didn't tested it after the merge. Please, make sure that after a new release we'll get the right docker image at DockerHub

**Comment by dvaumoron** [comment]
I have seen that the Dockerfile does not contains the `tofu` and `terraform` proxy commands. `tenv` alone does not seems very useful.

**Comment by kvendingoldo** [comment]
Added tofu/terraform/terragrunt proxies to Dockerfile.
