### ISSUE TITLE
Improve the ZSH completion guide

### ISSUE THREAD

**Issue by samuel-phan** [tofuutils/tenv#151]
**Describe the bug**
The ZSH completion instructions should include guidance for those using "Oh My Zsh" plugin.

**To Reproduce**
N/A.

**Expected behavior**
In the section https://github.com/tofuutils/tenv?tab=readme-ov-file#install-shell-completion , we should have zsh+Oh My Zsh instructions.

This guy explains a bit how zsh completion works:
https://stackoverflow.com/a/66145365/3538173

It's more the idiomatic way to add a new zsh completion with Oh My Zsh, and the completion filename MUST be `_tenv`.

**Screenshots**
N/A.

**Environment (please complete the following information):**
- OS: Ubuntu 22
- tofuenv version v1.11.6

**Additional context**
N/A.

**Comment by kvendingoldo** [comment]
@samuel-phan Thank you for the issue! Can you send a PR with updated documentation as you can see it, please?
