### ISSUE TITLE
Update Makefile

### ISSUE THREAD

**Issue by kvendingoldo** [tofuutils/tenv#16]

**Comment by JonZeolla** [comment]
Or possibly use an alternative? I like [taskfiles](https://taskfile.dev/)

**Comment by kvendingoldo** [comment]
@JonZeollaMakefile Makefile does not require any further installation and is available by default on all *nix-like platforms. I believe we can utilize Taskfile, but we need to ensure that it provides more options than the present Makefile. Have you used Taskfile on any real-world projects? It'd be interesting to hear.

**Comment by JonZeolla** [comment]
I agree that one downside is that it's an additional dependency.  

Here's some public places I've used it:
- https://github.com/SeisoLLC/cookiecutter-python/blob/main/Taskfile.yml
- https://github.com/SeisoLLC/goat/blob/main/Taskfile.yml
- https://github.com/SeisoLLC/easy_infra/blob/main/Taskfile.yml

**Comment by kvendingoldo** [comment]
I will check them!

**Comment by kvendingoldo** [comment]
Decided to keep Makefile as is.
