### ISSUE TITLE
tenv Terragrunt on Windows - missing .exe extension

### ISSUE THREAD

**Issue by silic2020** [tofuutils/tenv#162]
**Describe the bug**
Tenv Terragrunt installed with chocolatey does not work on Windows. 
To resolve, you have to rename yourself the executable file , by adding the .exe.

**To Reproduce**
1. install tenv with chocolatey : choco install tenv
2. install Terragrunt last version : tenv tg install 
3. try to use Terragrunt : Terragrunt init
4. You'll get this error : 
Failure during terragrunt call : exec: "C:\\Users\\xxxxxx\\.tenv\\Terragrunt\\0.58.14\\terragrunt": file does not exist

**Additional context**
Open the executable file location (here in folder C:\Users\xxxxxx\.tenv\Terragrunt\0.58.14).
Rename terragrunt by terragrunt.exe , terragrunt will work fine now

**Comment by kvendingoldo** [comment]
we'll fix it soon, that you for reporting

**Comment by kvendingoldo** [comment]
hmm, that's strange, I see that we add extension here https://github.com/tofuutils/tenv/blob/2e22c969419e6134adf691d0a37656a549dbdff7/versionmanager/retriever/terragrunt/terragruntretriever.go#L146
we'll continue to investigate it

**Comment by kvendingoldo** [comment]
Looks like that I found the issue:
https://github.com/tofuutils/tenv/blob/main/config/config.go#L39

I think that here we have to change  return based on runtime.GOOS
https://github.com/tofuutils/tenv/blob/2e22c969419e6134adf691d0a37656a549dbdff7/versionmanager/retriever/terragrunt/terragruntretriever.go#L110C55-L110C69

**Comment by kvendingoldo** [comment]
@silic2020 may I ask you to try version 2.0.4 when it will be available at choco, please?

**Comment by silic2020** [comment]
> @silic2020 may I ask you to try version 2.0.4 when it will be available at choco, please?

@kvendingoldo I've tried with the latest version 2.0.5. The error is the same : "file does not exist". The file extension ".exe" is now present, but the terragrunt file is incorrectly named. Instead of having "terragrunt.exe" I get "terragrunt_windows_amd64.exe"

**Comment by dvaumoron** [comment]
v2.0.7 work on Windows (I tested on a x86_64)

**Comment by silic2020** [comment]
also tested with v.20.7,  thks it works great!
