### ISSUE TITLE
go install -v github.com/tofuutils/tenv/cmd/tenv@latest installing version 1

### ISSUE THREAD

**Issue by kron4eg** [tofuutils/tenv#176]
**Describe the bug**
Since you have tagged v2 version of the package, can you also please update go.mod file, with

```
module github.com/tofuutils/tenv/v2
```

To make it go install-able again.

**To Reproduce**
```
$ go install -v github.com/tofuutils/tenv/cmd/tenv@latest
go: downloading github.com/tofuutils/tenv v1.11.19
```

**Expected behavior**

`go install -v github.com/tofuutils/tenv/cmd/tenv/v2@latest` will install latest v2.

**Environment (please complete the following information):**
- OS: any
- tofuenv version: v2.x.x

**Comment by kvendingoldo** [comment]
https://github.com/tofuutils/tenv/pull/177

**Comment by kvendingoldo** [comment]
looks like that quick fix didn't help. Will check it later

**Comment by kron4eg** [comment]
Original command from the description had `/v2` in the wrong place. Actual command looks like this:

```
$ go install -v github.com/tofuutils/tenv/v2/cmd/...@latest
go: downloading github.com/tofuutils/tenv/v2 v2.1.7
github.com/tofuutils/tenv/v2/pkg/reversecmp
github.com/tofuutils/tenv/v2/pkg/winbin
```
