### ISSUE TITLE
Remove deprecated usage

### ISSUE THREAD

**Issue by dvaumoron** [tofuutils/tenv#188]
`tenv list`, etc. have been deprecated in favor of `tenv tofu list` to align all the tools, is it time to get rid of that ?

And no longer accept `tenv install` and other command without the tool subcommand.

This will allows to clean the code of the test for deprecation and corresponding messages.

**Comment by kvendingoldo** [comment]
Agree, these commands should be definitely deprecated and removed in the next 2-3 releases.
