### ISSUE TITLE
Fix golang-ci lint issues

### ISSUE THREAD

**Issue by kvendingoldo** [tofuutils/tenv#19]

**Comment by dvaumoron** [comment]
most golang-ci lint issues are linked to the added functions in go stdlib in 1.21 versus 1.18

**Comment by kvendingoldo** [comment]
I think that we can disable linter via comment for these functions

**Comment by dvaumoron** [comment]
I am correcting some of the issues... But other, like G107 (HTTP request made with variable url) can not be changed, as we want to provide to users the ability to choose. I will carrect when it seems possible and add `//nolint` elsewhere...

**Comment by dvaumoron** [comment]
What do you think about `fmt.Println` errors ? I find  overkill to use a log lib for cli display...

**Comment by kvendingoldo** [comment]
@dvaumoron agree about `Println` issues; Let's use `// nolint` comment for such cases

**Comment by kvendingoldo** [comment]
If you need any help with golint issues, I will able to work on it today's evening

**Comment by dvaumoron** [comment]
Everything seem ok on GitHub (my local installation of golangci-lint have a different behaviour, not digged why yet)

**Comment by kvendingoldo** [comment]
@dvaumoron I also have the different results locally, but now we have green master. Good work!
