### ISSUE TITLE
tenv 2.2.0 breaks terraform fmt with nvim lsp and terraform-ls

### ISSUE THREAD

**Issue by verygitmuchhub** [tofuutils/tenv#191]
**Describe the bug**
nvim with terraform-ls, `terraform fmt` code on save results in the document being empty. Possibly something related to stdin/stdout, I guess. Downgrade to 2.1.8 reverted the behaviour and `terraform fmt` called from nvim lsp works again as expected.

**To Reproduce**
1. Install 2.2.0
2. Open terraform code in nvim with terraform-ls
3. Save file with autocommand `terraform fmt`

**Expected behavior**
nvim receives formatted code output from terraform fmt and updates the buffer.

**Environment (please complete the following information):**
- OS: Arch Linux
- tofuenv version 2.2.0

**Additional context**

* (minimal) nvim configuration

This is untested configuration and for illustration purposes.

```lua
require('lazy').setup({
  {
    'neovim/nvim-lspconfig',
    config = function()
      local lsp_capabilities = vim.lsp.protocol.make_client_capabilities()
      lsp_capabilities = require('cmp_nvim_lsp').default_capabilities(lsp_capabilities)
      lsp_capabilities.textDocument.completion.completionItem.snippetSupport = true

      local lsp_signature_cfg = {}

      if vim.fn.executable('terraform-ls') == 1 then
        local augroup = vim.api.nvim_create_augroup('LspFormatting', {})
        lsp_config.terraformls.setup({
          capabilities = lsp_capabilities,
          on_attach = function(client, bufnr)
            require('lsp_signature').on_attach(lsp_signature_cfg, bufnr)
            if client.supports_method('textDocument/formatting') then
              vim.api.nvim_clear_autocmds({ group = augroup, buffer = bufnr })
              vim.api.nvim_create_autocmd({ 'BufWritePre' }, {
                group = augroup,
                buffer = bufnr,
                callback = function()
                  vim.lsp.buf.format({ bufnr = bufnr })
                end
              })
            end
          end,
        })
      end
    end
  }
})
```

**Comment by kvendingoldo** [comment]
@dvaumoron looks like that we have to revert changes related to proxy for a while

**Comment by dvaumoron** [comment]
Find something, I will fix

**Comment by dvaumoron** [comment]
@verygitmuchhub , can you check that things work as expected with v2.2.1 ?
