### ISSUE TITLE
tenv 2.2.0 breaks terraform apply: `error asking for approval: EOF`

### ISSUE THREAD

**Issue by ThibaultNocchi** [tofuutils/tenv#192]
**Describe the bug**
In tenv 2.2.0, I can't apply as I can't answer `yes` to the prompt:

```bash
Plan: 0 to add, 1 to change, 0 to destroy.
╷
│ Warning: Resource targeting is in effect
│
│ You are creating a plan with the -target option, which means that the result of this plan may not
│ represent all of the changes requested by the current configuration.
│
│ The -target option is not for routine use, and is provided only for exceptional situations such
│ as recovering from errors or mistakes, or when Terraform specifically suggests to use it as part
│ of an error message.
╵

Do you want to perform these actions in workspace "nonprod"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: ╷
│ Error: error asking for approval: EOF
│
│
╵
```

I'm guessing it may be linked to #191.

**To Reproduce**
1. Ensure tenv is v2.2.0
2. Run a manual TF apply
3. Get the error message, which stops the apply procedure

**Expected behavior**
EOF shouldn't be fed to the terraform binary I guess?

**Screenshots**

**Environment (please complete the following information):**
- OS: ArchLinux
- tofuenv version: 2.2.0
- terraform: 1.8.4-5 (I haven't tested others)

**Additional context**
I rollbacked to 2.1.8 and it works.

**Comment by kvendingoldo** [comment]
Thank you for reporting, we'll check it asap

**Comment by dvaumoron** [comment]
@ThibaultNocchi, can you check that things work as expected with v2.2.1 ?

**Comment by voron** [comment]
2.2.1  fixed it for me

**Comment by ThibaultNocchi** [comment]
It also works for me, thank you for the quick fix!
