### ISSUE TITLE
TENV_AUTO_INSTALL is not working

### ISSUE THREAD

**Issue by myoung34** [tofuutils/tenv#198]
**Describe the bug**

I have `TENV_AUTO_INSTALL` set to true, but tenv refuses to acknowlege it

**To Reproduce**

```
➜  talos git:(main) echo $TENV_AUTO_INSTALL
true
➜  talos git:(main) tenv tf detect -n
Resolved version from .terraform-version : 1.9.0
Auto-install is disabled. To install Terraform version 1.9.0, you can set environment variable TENV_AUTO_INSTALL=true, or install it via any of the following command: 'tenv terraform install', 'tenv terraform install 1.9.0'
no compatible version found locally
Terraform 1.9.0 will be run from this directory.
```

**Expected behavior**

tfenv should install what's in .terraform-version

**Screenshots**

**Environment (please complete the following information):**
- OS: `NixOS 24.11 (Vicuna)`
- tofuenv version: `v2.2.1`

**Additional context**

**Comment by kvendingoldo** [comment]
Looks like a bug. Thank you for reporting, we'll fix it

**Comment by dvaumoron** [comment]
Hi @myoung34, there is a `-n` flag (same as `--no-install`) in your command, this flag override the `TENV_AUTO_INSTALL` env var

**Comment by kvendingoldo** [comment]
@dvaumoron how do you think, do we still need this flag?

**Comment by dvaumoron** [comment]
as now, auto install default to disabled, it's strange to use `-n=false` to activate it with the flag, we should probably add a simpler `-i` (still with priority to `-n`)
