### ISSUE TITLE
Even if TFENV_HASHICORP_PGP_KEY is set, it is always treated as an empty character

### ISSUE THREAD

**Issue by tkyggit** [tofuutils/tenv#209]
**Describe the bug**

TFENV_HASHICORP_PGP_KEY is not reflected

**To Reproduce**
1. Define TENV_ROOT as ‘c:¥tenv’
2. Make repository file c:¥tenv¥remote.yaml

> terraform:
>   url: “https://mymirror”
>    Install_mode: “direct”
>    list_mode:  “html”

3. Set TFENV_HASHICORP_PGP_KEY

>  $env: TFENV_HASHICORP_PGP_KEY=‘c:¥test.txt’

4. Execute cli ‘tenv terraform install’

ignore TFENV_HASHICORP_PGP_KEY like below

> Downloading https://www.hashicorp.com/.well-known/pgp-key.txt

**Expected behavior**

TFENV_HASHICORP_PGP_KEY setting should be reflected

**Environment (please complete the following information):**
- OS: [Windows 10]
- tenv version [2.5.0]

**Comment by dvaumoron** [comment]
reproduced with 2.6.0, however the `-k` flag work as expected (after some research it seems Windows need a restart, then  `os.Getenv` will see the new environement variable)
