### ISSUE TITLE
docs: add guidance around verifying tenv using cosign

### ISSUE THREAD

**Issue by kieran-lowe** [tofuutils/tenv#215]
### Discussed in https://github.com/tofuutils/tenv/discussions/212

<div type='discussions-op-text'>

<sup>Originally posted by **kieran-lowe** July 17, 2024</sup>
Hi all, 

Not sure if I'm missing something obvious, but I'm really struggling to verify the signatures for tenv. I've tried using GPG, OpenSSL and cosign but not having any luck. Maybe worth adding some documentation on the process?

I noticed the .pem file is base64 encoded but when using the output in cosign it's asking for certificate identity etc

Sorry if this is a stupid question!

Cheers,
Kieran</div>

**Comment by dvaumoron** [comment]
I think the cosign check on the sha file was enough, if the rpm is corrupted, I suppose the sha check will spot that
