### ISSUE TITLE
Publish linux arm64 image to dockerhub

### ISSUE THREAD

**Issue by eepmoi** [tofuutils/tenv#217]
**Is your feature request related to a problem? Please describe.**
Hi folks - I want to use tenv in docker for my CI pipeline which runs on linux arm64.  It would be fantastic if you could publish an arm64 version to dockerhub, currently only amd.
https://hub.docker.com/r/tofuutils/tenv/tags?page=&page_size=&ordering=&name=

This saves me having to manually build an arm64 docker image for CI.

**Describe the solution you'd like**
Publish a linux arm64 image to dockerhub.

**Describe alternatives you've considered**
Crafting my own dockfile to install the linux arm64 binary.

**Additional context**
![image](https://github.com/user-attachments/assets/f7f10442-d983-4260-b299-3e000a9b1bdf)

Thanks for your time.

**Comment by kvendingoldo** [comment]
@eepmoi Hi! Thank you for the issue. Will add this support soon

**Comment by eepmoi** [comment]
Great thanks @kvendingoldo!

If it helps others, here's my Dockerfile.
```dockerfile
FROM public.ecr.aws/docker/library/alpine:3.20

# renovate: datasource=github-releases depName=tofuutils/tenv
ENV TENV_VERSION=2.6.1

ADD https://github.com/tofuutils/tenv/releases/download/v${TENV_VERSION}/tenv_v${TENV_VERSION}_Linux_arm64.tar.gz /tmp
RUN tar -xvzf /tmp/tenv_v${TENV_VERSION}_Linux_arm64.tar.gz -C /usr/bin

WORKDIR /workdir

COPY .terraform-version .
RUN TF_VERSION=$(cat .terraform-version) && \
  echo "Using Terraform version $TF_VERSION" && \
  tenv tf use $TF_VERSION --install

CMD ["terraform"]
```

With renovate config snippet for those who use it:
```json
  "customManagers": [
    {
      "customType": "regex",
      "description": "Update _VERSION variables in Dockerfiles",
      "fileMatch": ["(^|/|\\.)Dockerfile$", "(^|/)Dockerfile\\.[^/]*$"],
      "matchStrings": [
        "# renovate: datasource=(?<datasource>.*?) depName=(?<depName>.*?)( versioning=(?<versioning>.*?))?\\s(?:ENV|ARG) .*?_VERSION=(?<currentValue>.*)\\s"
      ]
    }
  ]

```

**Comment by kvendingoldo** [comment]
@eepmoi looks like it's done :) 
<img width="1201" alt="Screenshot 2024-07-26 at 04 07 07" src="https://github.com/user-attachments/assets/60f7e59e-0524-4f3a-90ce-84173d18747a">
