### ISSUE TITLE
Interactive mode support

### ISSUE THREAD

**Issue by kvendingoldo** [tofuutils/tenv#219]
I spoke with some people, and they mentioned that tenv is a little bit complex. I asked what they wouldn't like to see and what was preventing them from using tenv and received the following response:

> At this moment, tenv requires a lot of additional flags to setup a version. I would like to have the interactive version pickup, after the launch of tenv tool, where I can choose the version. tenv with no args give me help message and exited

@dvaumoron how do you think, is it possible to implement anyhow in the current tool architecture?

**Comment by dvaumoron** [comment]
A call without subcommand (technically need to bypass cobra) could allow to choose the tool, then for the selected one, a management list (similar to interactive uninstall, however based on list-remote, with already installed prevalidated) to allow to install/uninstall any version.

Do you think it will satisfy most users ?

**Comment by kvendingoldo** [comment]
yep, plus I think that it will increase an amount of our users

**Comment by dvaumoron** [comment]
@kvendingoldo, do you think this feature worth a v3 ?

**Comment by kvendingoldo** [comment]
@dvaumoron I think so!
