### ISSUE TITLE
add terratest to the supported tools

### ISSUE THREAD

**Issue by tbugfinder** [tofuutils/tenv#225]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated by managing versions of my terraform and tofu tooling. As terratest is also being used, this is not supported yet in tenv.

**Describe the solution you'd like**
Terratest is another tool being used within the terraform / tofu space. It would be very beneficial to also manage it using tenv.

**Describe alternatives you've considered**
Maintain terratest versions on my own.
Actually this sounds like a go version manager, though (sort of).

**Additional context**
N/A

REF: https://github.com/gruntwork-io/terratest

**Comment by kvendingoldo** [comment]
We have the similar request about tflint / trivy: https://github.com/tofuutils/tenv/issues/210
Do you think, that terratest requires anything more than just a version update? Please, describe your case a little bit more

**Comment by tbugfinder** [comment]
Well, as updated above it's more a go version manager then.
AFAICT, it's just about pulling the proper version and maybe set ENV variables depending on how the installation is applied.

Terratest is based on go test and the terratest code versions are maintained within go.mod/go.sum.

I would just be helpful to support GO version management within tenv instead of incorporating asdf.

**Comment by tbugfinder** [comment]
In order to leverage terratest (go get..), go is a pre-requisite. As mentioned above this request might rather sound like a go version manager backed into tenv. It would just allow us to use a single tool for managing dependencies.

**Comment by tbugfinder** [comment]
Your point is taken 😃
I'll look into gvm / goenv.

Thank you!
