### ISSUE TITLE
Authentication support

### ISSUE THREAD

**Issue by adongy** [tofuutils/tenv#226]
**Is your feature request related to a problem? Please describe.**
Hello, when using a remote configuration to use Artifactory for example, there is no documented way to use credentials (.netrc or user/password in URL)

**Describe the solution you'd like**
Document (and implement if needed) how to specify credentials to authenticate to a remote.

**Describe alternatives you've considered**

**Additional context**
tofuenv explicitely supports .netrc for that usecase.

Thanks!

**Comment by dvaumoron** [comment]
`http.Get` in [net/http](https://pkg.go.dev/net/http) does not seem to handle `.netrc`. So this need an implementation step.

**Comment by dvaumoron** [comment]
`https://user:password@host.org` should work, however I can add some env var to have a better support.
