### ISSUE TITLE
[tfswitch-parity] tofuenv latest-pre {major.minor}

### ISSUE THREAD

**Issue by kvendingoldo** [tofuutils/tenv#24]
**Describe the solution you'd like**
Please replicate this feature from tfswitch. https://tfswitch.warrensbox.com/Quick-Start/#install-latest-implicit-version-for-beta-alpha-and-release-candidatesrc

Helps with testing Terraform code/modules against upcoming releases in a CI pipeline.

**Additional context**
It's backport of the original issue from tofuenv: https://github.com/tofuutils/tofuenv/issues/30
cc @skyzyx

**Comment by dvaumoron** [comment]
The latest feature in the current version does not make distinction on stable or unstable version for Terraform, however the behaviour on OpenTofu version depend on the latest shortcut in the Github API which depend on the release tagged latest by the OpenTofu team.

It is possible to add a latest-pre behaviour, and maybe latest should be aliased to latest-stable, what do you think ?
