### ISSUE TITLE
Does not work with terraform -chdir or modules

### ISSUE THREAD

**Issue by OJFord** [tofuutils/tenv#246]
**Describe the bug**
It seems tenv only scans terraform files in the current directory.

If all such files are in a `tf` subdirectory say, with a `tf/.terraform-version` of `min-required` and `tf/providers.tf` having `terraform { required_version = "~> 1.5" }`, then:
```
$terraform -chdir=tf version
Resolved version from .terraform-version : min-required
Scan project to find IAC files
No Terraform version requirement found in project files, fallback to latest strategy
[...]
```

(note also that that requires `.terraform-version` in `$PWD` - it won't find that from the `-chdir` either)

Even without `-chdir`, if there's additionally a `tf/module/providers.tf` with a `terraform { required_version = "~> 1.9" }` say, then:
```
$cd tf && terraform version
Resolved version from [..]/.terraform-version : min-required
Scan project to find IAC files
No compatible version found locally, search a remote one...
Fetching all releases information from https://releases.hashicorp.com/terraform/index.json
Found compatible version remotely : 1.5.0
Installing Terraform 1.5.0
```

ignoring the 1.9 requirement.

**To Reproduce**
Described above

**Expected behavior**
1.9.0 installed in both cases, with or without `-chdir`, 1.5.0 is _not_ compatible.

**Screenshots**
N/A

**Environment (please complete the following information):**
- OS: [e.g. iOS] macOS (iOS?!)
- ~tofuenv~ tenv version [e.g. 0.8.0] 3.1.0

**Additional context**
N/A

**Comment by OJFord** [comment]
Thinking about it some more, arguably ignoring modules is ok, since `tf/providers.tf` is _wrong_ to say `~> 1.5` if that module uses `./module` which has `~> 1.9` in `tf/module/providers.tf`, but `-chdir` should work.

**Comment by dvaumoron** [comment]
Hi @OJFord ,

Indeed avoiding subdirectory  is better for most users (see [this issue](https://github.com/tofuutils/tenv/issues/89))

However, I think we can handle `-chdir`

**Comment by OJFord** [comment]
Well there is a difference between a module used by the current working (or given) directory's config and any old subdirectory (as described in that issue, and which indeed could be a module used by another but not this one, or just an independent project).

However as I mentioned in my comment above I do think it makes sense to ignore modules anyway: if you use a module that requires a certain tf version, then your own `required_version` should be compatible with (i.e. equal or stricter than) that anyway.
