### ISSUE TITLE
[tfswitch-parity] Auto-install if a .tf file contains a Terraform required_version block

### ISSUE THREAD

**Issue by kvendingoldo** [tofuutils/tenv#25]
**Describe the solution you'd like**
Please replicate this feature from tfswitch. https://tfswitch.warrensbox.com/Quick-Start/#use-versiontf-file

**Additional context**
It's backport of the original issue from tofuenv: https://github.com/tofuutils/tofuenv/issues/31
cc @skyzyx

**Comment by dvaumoron** [comment]
The default behaviour (when no .opentofu-version or .terraform-version files are found, depending on which proxy command you use) of current version is latest-allowed which scan .tf and .tf.json files to extract required_version constraints.

**Comment by giner** [comment]
> The default behaviour (when no .opentofu-version or .terraform-version files are found, depending on which proxy command you use) of current version is latest-allowed which scan .tf and .tf.json files to extract required_version constraints.

This works unless (surprisingly) the default version is defined

**Comment by dvaumoron** [comment]
Hi @giner ,

starting to scan the whole folder before simpler checks does not seem accurate to me.

the resolution ordrer for reference : https://github.com/tofuutils/tenv#project-binaries 

`tenv` look for a `TOFUENV_TOFU_DEFAULT_VERSION ` environment variable after most files have been tested.

**Comment by giner** [comment]
> starting to scan the whole folder before simpler checks does not seem accurate to me

From implementation perspective this makes sense, however from UX perspective the current behavior is not optimal an not vey obvious. If required_version was considered earlier (with higher priority) we wouldn't need .xxx-version files in most cases.

> tenv look for a TOFUENV_TOFU_DEFAULT_VERSION environment variable after most files have been tested.

I believe this should be changed. Here's a proposal https://github.com/orgs/tofuutils/discussions/7#discussioncomment-11941382
