### ISSUE TITLE
Add an ability to download Terraform from GitHub

### ISSUE THREAD

**Issue by kvendingoldo** [tofuutils/tenv#252]
**Is your feature request related to a problem? Please describe.**
In some cases, defaultHashicorpURL ("https://releases.hashicorp.com") can be unavailable. E.g.: in a system, where the security department allowed only access to GitHub.  

**Describe the solution you'd like**
It should be an ability to download Terraform from GitHub as well as OpenTofu or Terragrunt.

**Comment by dvaumoron** [comment]
I don't see any Terraform binaries on Github (see [here](https://github.com/hashicorp/terraform/releases))
