### ISSUE TITLE
Avoid shipping proxies as standalone binaries

### ISSUE THREAD

**Issue by adongy** [tofuutils/tenv#253]
**Is your feature request related to a problem? Please describe.**
Currently, proxies are standalone binaries that are separate from tenv, while reusing a big part of the code.
This style of binary that embeds multiple functionalities is not unique, for example busybox behaves as its subcommands if called from a symlink (hard or soft).

It does so by reading argv[0] which is also possible in Go.

**Describe the solution you'd like**
Instead of creating multiple cmds for each proxy, implement it in the tenv command by reading os.Args[0] and if it's in the cmdconst values, call the proxy instead of tenv.

**Describe alternatives you've considered**
Keep the current binaries as-is.

**Additional context**
Note that it would then be impossible to call the proxies with an executable name that is *not* named the proxy: currently you could rename the terraform proxy binary anything else and it would still work.

**Comment by dvaumoron** [comment]
the hidden behavior work as 'tenv call <tool> [args ...]'
