### ISSUE TITLE
Transparently support `.terraform-version`

### ISSUE THREAD

**Issue by kvendingoldo** [tofuutils/tenv#26]
**Describe the solution you'd like**
Perform the same actions when a `.terraform-version` file is found, as when an `.opentofu-version` file is found.

**Additional context**
It's backport of the original issue from tofuenv: https://github.com/tofuutils/tofuenv/issues/32
cc @skyzyx

**Comment by dvaumoron** [comment]
The actual `tenv tf` subcomands and `terraform` proxy command try to read `.terraform-version` in working directory, use home directory and TOFUENV_ROOT (alias TFENV_ROOT and default` $HOME/.tenv`)

**Comment by kvendingoldo** [comment]
@dvaumoron looks like that you have already covered this case. Feel free to close it
