### ISSUE TITLE
alpine version still on v2.0.2

### ISSUE THREAD

**Issue by cra-schleupen** [tofuutils/tenv#265]
**Describe the bug**
When installing tenv on alpine, as described in docs, I get v2.0.2

**To Reproduce**
Dockerfile:
```
FROM alpine:latest

RUN apk add tenv --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/

CMD ["tenv", "--version"]
```

Build and run:

```
$ docker build . -t issue
[...]
$ docker run issue
tenv version v2.0.2
```

**Expected behavior**
apk version should install an up-to-date version.

**Comment by kvendingoldo** [comment]
updated it manually for now, we'll automate it soon
https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/73739/diffs
