### ISSUE TITLE
[tfswitch-parity] Support version ranges defined in terragrunt.hcl

### ISSUE THREAD

**Issue by kvendingoldo** [tofuutils/tenv#27]
**Describe the solution you'd like**
Please replicate this feature from tfswitch. https://tfswitch.warrensbox.com/Quick-Start/#use-terragrunthcl-file

**Additional context**
It's backport of the original issue from tofuenv: https://github.com/tofuutils/tofuenv/issues/33
cc @skyzyx

**Comment by dvaumoron** [comment]
Does not seem complicated to do (there is already hcl parsing for .tf files), what should be the prioritiy order ? I suggest forcing env var , then version files (.opentofu-version or .terraform-version), then terragrunt.hcl file, and last scanning for .tf files

I want to underline that if we continue to add support for more ways to choose a version to use, the priority rules should be clearly indicated by the documentation.

**Comment by dvaumoron** [comment]
Change done, however the code in semantic.go is not very readeable, i will think about a way to refactor it.

**Comment by dvaumoron** [comment]
I think that's better. Any remark ?

**Comment by kvendingoldo** [comment]
@dvaumoron I think so! Great!
