### ISSUE TITLE
[tfswitch-parity] Support a default version unless a more specific version is requested

### ISSUE THREAD

**Issue by kvendingoldo** [tofuutils/tenv#28]
**Describe the solution you'd like**
Please replicate this feature from tfswitch. https://tfswitch.warrensbox.com/Quick-Start/#set-a-default-tf-version-for-cicd-pipeline

**Additional context**
It's backport of the original issue from tofuenv: https://github.com/tofuutils/tofuenv/issues/34
cc @skyzyx

**Comment by dvaumoron** [comment]
The `tenv use` already allows that, or do i miss something ?
