### ISSUE TITLE
Getting `Error: unexpected value returned by API` when trying to install latest OpenTofu version using tenv

### ISSUE THREAD

**Issue by kieran-lowe** [tofuutils/tenv#287]
**Describe the bug**

When running `tenv tofu install latest` or running `tenv` and configuring OpenTofu I get the following error message:

```bash
> tenv tofu install latest
Fetching all releases information from https://api.github.com/repos/opentofu/opentofu/releases
Error: unexpected value returned by API
```

**To Reproduce**
1. Run `tenv tofu install latest`
2. See error

**Expected behavior**
To install the latest version of OpenTofu

**Screenshots**
<img width="635" alt="Screenshot 2024-11-23 at 11 53 49" src="https://github.com/user-attachments/assets/0e505b56-f2ce-49bf-b927-7d74d4e2cc3e">

**Environment (please complete the following information):**
- OS: Linux (GH Codespaces/VSCode)
- tenv version v3.2.10

**Additional context**
If I run `tenv tofu install 1.8.5` it installs successfully without issues.

**Comment by Nmishin** [comment]
Hmm, tested it right now and can't reproduce:
```
% tenv tofu install latest
Fetching all releases information from https://api.github.com/repos/opentofu/opentofu/releases
Found compatible version remotely : 1.8.6
Installing OpenTofu 1.8.6
Fetching release information from https://api.github.com/repos/opentofu/opentofu/releases/tags/v1.8.6
Downloading https://github.com/opentofu/opentofu/releases/download/v1.8.6/tofu_1.8.6_darwin_arm64.zip
Downloading https://github.com/opentofu/opentofu/releases/download/v1.8.6/tofu_1.8.6_SHA256SUMS
Downloading https://github.com/opentofu/opentofu/releases/download/v1.8.6/tofu_1.8.6_SHA256SUMS.sig
Downloading https://github.com/opentofu/opentofu/releases/download/v1.8.6/tofu_1.8.6_SHA256SUMS.pem
cosign executable not found, fallback to pgp check
Downloading https://github.com/opentofu/opentofu/releases/download/v1.8.6/tofu_1.8.6_SHA256SUMS.gpgsig
Downloading https://get.opentofu.org/opentofu.asc
Installation of OpenTofu 1.8.6 successful
% tenv version
tenv version 3.2.10
```

@kieran-lowe kieran-lowe did you run tenv multiple times before you get this error? It can be a GitHub rate limiting I believe

**Comment by kieran-lowe** [comment]
> Hmm, tested it right now and can't reproduce:
> 
> ```
> % tenv tofu install latest
> Fetching all releases information from https://api.github.com/repos/opentofu/opentofu/releases
> Found compatible version remotely : 1.8.6
> Installing OpenTofu 1.8.6
> Fetching release information from https://api.github.com/repos/opentofu/opentofu/releases/tags/v1.8.6
> Downloading https://github.com/opentofu/opentofu/releases/download/v1.8.6/tofu_1.8.6_darwin_arm64.zip
> Downloading https://github.com/opentofu/opentofu/releases/download/v1.8.6/tofu_1.8.6_SHA256SUMS
> Downloading https://github.com/opentofu/opentofu/releases/download/v1.8.6/tofu_1.8.6_SHA256SUMS.sig
> Downloading https://github.com/opentofu/opentofu/releases/download/v1.8.6/tofu_1.8.6_SHA256SUMS.pem
> cosign executable not found, fallback to pgp check
> Downloading https://github.com/opentofu/opentofu/releases/download/v1.8.6/tofu_1.8.6_SHA256SUMS.gpgsig
> Downloading https://get.opentofu.org/opentofu.asc
> Installation of OpenTofu 1.8.6 successful
> % tenv version
> tenv version 3.2.10
> ```
> 
> @kieran-lowe kieran-lowe did you run tenv multiple times before you get this error? It can be a GitHub rate limiting I believe

It was the first time that I ran it as it was a brand new GitHub Codespace. I've just tried running it again now and it's all working okay... so not sure what happened. I noticed OpenTofu released a new version yesterday, but not sure if that had anything to do with it.

Will keep an eye on it and close this.

**Comment by dvaumoron** [comment]
Add a github token ?
