### ISSUE TITLE
[tfswitch-parity] Transparently support .tfswitchrc files.

### ISSUE THREAD

**Issue by kvendingoldo** [tofuutils/tenv#29]
**Describe the solution you'd like**
Please replicate this feature from tfswitch. https://tfswitch.warrensbox.com/Quick-Start/#use-tfswitchrc-file

**Additional context**
It's backport of the original issue from tofuenv: https://github.com/tofuutils/tofuenv/issues/35
cc @skyzyx

**Comment by dvaumoron** [comment]
Priority between .tfswitchrc and .terraform-version files ? Do we need to support something like .tofuswitchrc for the OpenTofu part ?

**Comment by dvaumoron** [comment]
Changed to check .tfswitchrc in working directory after .terraform-version there, and before user home directory or root directory (no search of .tfswitchrc in those other places).

No modification on the OpenTofu management.
