### ISSUE TITLE
Cannot do "list-remote"

### ISSUE THREAD

**Issue by notorand-it** [tofuutils/tenv#296]
**Describe the bug**
Both `tenv tf list remote` and `tenv tofu list-remote` fail with "connection refused" message, while a `wget` on the same URL just works.
```
Fetching all releases information from https://releases.hashicorp.com/terraform/index.json
Error: Get "https://releases.hashicorp.com/terraform/index.json": dial tcp: lookup releases.hashicorp.com on [::1]:53: read udp [::1]:36894->[::1]:53: read: connection refused
```
Same goes for `tenv tf install 1.9.8` (or any other existing version).

**To Reproduce**
1. run `tenv tf list-remote` or `tenv tofu list-remote`
2. Check the remote resources are available via `wget`

**Expected behavior**
I list of remotely available versions to be displayed.

**Screenshots**
![SHOT-20241211-160715+0100](https://github.com/user-attachments/assets/b04e4b1a-b53c-4f12-9138-0b0ad93b8c04)

**Environment (please complete the following information):**
- OS: ArchLinux 8x86_64

- tenv version: 3.2.10 

**Additional context**
N/A

**Comment by notorand-it** [comment]
I suspect this has to do with my specific distro resolver configuration: also a trivial `nslookup` is failing: there is nothing "listening" on `[::1]:53`:
```
$ sudo ss -lunp | grep systemd-resolve
UNCONN 0      0            0.0.0.0:5353       0.0.0.0:*    users:(("systemd-resolve",pid=5554,fd=15))
UNCONN 0      0            0.0.0.0:5355       0.0.0.0:*    users:(("systemd-resolve",pid=5554,fd=11))
UNCONN 0      0         127.0.0.54:53         0.0.0.0:*    users:(("systemd-resolve",pid=5554,fd=24))
UNCONN 0      0      127.0.0.53%lo:53         0.0.0.0:*    users:(("systemd-resolve",pid=5554,fd=22))
UNCONN 0      0               [::]:5353          [::]:*    users:(("systemd-resolve",pid=5554,fd=16))
UNCONN 0      0               [::]:5355          [::]:*    users:(("systemd-resolve",pid=5554,fd=13))
$ sudo ss -ltnp | grep systemd-resolve
LISTEN 0      4096      127.0.0.54:53         0.0.0.0:*    users:(("systemd-resolve",pid=5554,fd=25))
LISTEN 0      4096   127.0.0.53%lo:53         0.0.0.0:*    users:(("systemd-resolve",pid=5554,fd=23))
LISTEN 0      4096         0.0.0.0:5355       0.0.0.0:*    users:(("systemd-resolve",pid=5554,fd=12))
LISTEN 0      4096            [::]:5355          [::]:*    users:(("systemd-resolve",pid=5554,fd=14))
``` 

Shall I close this issue? Any hint?

**Comment by notorand-it** [comment]
Yes, it's a (bug?) in my NetworkManager configuration  who wasn't aware of systemd-resolved.

**Comment by kvendingoldo** [comment]
Anyway, thank you for raising the issue!
