### ISSUE TITLE
Error: unexpected value returned by API on `tenv tg install latest`

### ISSUE THREAD

**Issue by mwos-sl** [tofuutils/tenv#297]
**Describe the bug**

Installing latest fails.

**To Reproduce**
Type `tenv tg install` results in:
```
No version files found for Terragrunt, fallback to latest strategy
Fetching all releases information from https://api.github.com/repos/gruntwork-io/terragrunt/releases
Error: unexpected value returned by API
```

Similarily for `tenv tg install latest`.

**Expected behavior**
`tenv tg install` should install latest available.

**Environment (please complete the following information):**
- docker container based on ubuntu 24
- tenv version v3.2.10

**Comment by kvendingoldo** [comment]
Hi @mwos-sl,
Thank you for reporting the issue. Can you share output of `tenv tg install -v`, please?

**Comment by kvendingoldo** [comment]
The first idea you may face with GitHub API rate limit (API rate limit exceeded)—I face it when I use a not dedicated public IP. To solve it, you can generate your personal token and set it via TENV_GITHUB_TOKEN env variable. Can you try it, please?

**Comment by Nmishin** [comment]
Also, you can try updating to the new version of tenv (v3.2.11). We have added improved handling for GitHub rate-limiting errors.
