### ISSUE TITLE
Please support `.tool-versions` file

### ISSUE THREAD

**Issue by tspearconquest** [tofuutils/tenv#301]
**Is your feature request related to a problem? Please describe.**
I'm working in an org which has recently adopted opentofu and tenv. I notice that tofuutils org has an asdf plugin for tenv, and you compare tenv with asdf. I have difficulty understanding why tenv doesn't support `.tool-versions` files.

I use asdf to install tools like kubectl and helm, and prior to my org adopting tenv, opentofu and atmos, I used it for terraform and terragrunt. asdf uses an in-repo config file named `.tool-versions` which lists the tools and their versions for that repo.

tenv uses a separate file for each tool, which is inconvenient and feels wholly unnecessary to me.

Additionally, we have team members who still use asdf for opentofu and atmos installation. Specifying the version for asdf users means we have to declare it twice, and the two version files can get out of sync, causing headaches.

**Describe the solution you'd like**
I'd like tenv to look for `.tool-versions` in the repo and read it if found. I'd like `.tool-versions` to take priority over any `.<toolname>-version` file but not over environment variables.

Supporting this would allow us to consolidate. We currently have a `.tool-versions` file for our asdf managed tools, and atmos and opentofu version files for the tenv managed tools. tenv could simply read the same file and ignore the tools it doesn't support.

It will also allow those who haven't switched (from an asdf installed atmos and opentofu to a tenv installed atmos and opentofu) to still rely on the same tool versions without needing to double declare by having them in a `.atmos-version` and `.opentofu-version` file alongside also having them in `.tool-versions` as we need to do today to support anyone who hasn't switched.

**Describe alternatives you've considered**
I thought of making a symbolic link for `.tool-versions` to the atmos version file but I need to include kubectl, helm, and opentofu, so a symbolic link is not going to accommodate this.

**Additional context**

**Comment by kvendingoldo** [comment]
Hi @tspearconquest! Thank you for reporting this issue. I agree that it makes sense to support .tools-version. We'll try to implement this support soon.

**Comment by Speeddymon** [comment]
Thanks! Please be aware it is `.tool-versions` rather than `.tools-version`

**Comment by dvaumoron** [comment]
done by @kvendingoldo in #303 , new release coming soon

**Comment by tspearconquest** [comment]
Unfortunately, it doesn't appear to be working. I removed `.opentofu-version`, then ran `asdf local opentofu 1.8.6` to create `.tool-versions`, then ran `tenv tofu install` to try to install opentofu 1.8.6 via tenv.

```
$ pwd
/tmp
$ ls -la 2>/dev/null |grep version
-rw-r--r-- 1  502 dialout     5 Dec 23 18:46 .opentofu-version
-rw-r--r-- 1  502 dialout    29 Dec 23 16:54 .tool-versions
$ cat .opentofu-version
1.8.6
$ cat .tool-versions
opentofu 1.8.6
$ tenv tofu install
Resolved version from /tmp/.opentofu-version : 1.8.6
Installing OpenTofu 1.8.6
Fetching release information from https://api.github.com/repos/opentofu/opentofu/releases/tags/v1.8.6
^c
$ rm -fv .opentofu-version
removed '.opentofu-version'
$ tenv tofu install
No version files found for OpenTofu, fallback to latest strategy
Fetching all releases information from https://api.github.com/repos/opentofu/opentofu/releases
^C
```

Please help check what I've done wrong.

**Comment by tspearconquest** [comment]
Further testing reveals it does seem to be working fine for atmos, just not for opentofu.

My CI gives the following:

```
$ tenv tofu install
No version files found for OpenTofu, fallback to latest strategy
Fetching all releases information from https://api.github.com/repos/opentofu/opentofu/releases
Found compatible version remotely : 1.8.7
Installing OpenTofu 1.8.7
Fetching release information from https://api.github.com/repos/opentofu/opentofu/releases/tags/v1.8.7
Downloading https://github.com/opentofu/opentofu/releases/download/v1.8.7/tofu_1.8.7_linux_amd64.zip
Downloading https://github.com/opentofu/opentofu/releases/download/v1.8.7/tofu_1.8.7_SHA256SUMS
Downloading https://github.com/opentofu/opentofu/releases/download/v1.8.7/tofu_1.8.7_SHA256SUMS.sig
Downloading https://github.com/opentofu/opentofu/releases/download/v1.8.7/tofu_1.8.7_SHA256SUMS.pem
cosign executable not found, fallback to pgp check
Downloading https://github.com/opentofu/opentofu/releases/download/v1.8.7/tofu_1.8.7_SHA256SUMS.gpgsig
Downloading https://get.opentofu.org/opentofu.asc
Installation of OpenTofu 1.8.7 successful
$ tenv atmos install
Resolved version from /opt/jenkins_agent/workspace/re_switch_to_tool_versions_files/.tool-versions : 1.115.0
Installing Atmos 1.115.0
Fetching release information from https://api.github.com/repos/cloudposse/atmos/releases/tags/v1.115.0
Downloading https://github.com/cloudposse/atmos/releases/download/v1.115.0/atmos_1.115.0_linux_amd64
Downloading https://github.com/cloudposse/atmos/releases/download/v1.115.0/atmos_1.115.0_SHA256SUMS
Installation of Atmos 1.115.0 successful
```

Further down when it tries to run tofu:

```
$ tofu fmt -check -recursive
Failure during tofu call : fork/exec /usr/bin/tenv: inappropriate ioctl for device
```

**Comment by tspearconquest** [comment]
#307 should fix this. Apologies as I'm not very good with Go.
