### ISSUE TITLE
Add `TENV_LOG=DEBUG` environment variable for logs

### ISSUE THREAD

**Issue by samuel-phan** [tofuutils/tenv#41]
**Is your feature request related to a problem? Please describe.**

When I want to have DEBUG logs, it's not convenient on a user perspective to have to set either `TOFUENV_VERBOSE` or `TFENV_VERBOSE`.

Moreover, there's no granularity in the log level.

**Describe the solution you'd like**

Let's not fall into the NIH (Not Invented Here) syndrome, and do just the same as Terraform / Tofu, i.e.:

```
TENV_LOG=DEBUG
```

Possible values:

- `TRACE`
- `DEBUG`
- `WARN`
- `INFO`
- `ERROR`

Doc:

- https://developer.hashicorp.com/terraform/internals/debugging
- https://opentofu.org/docs/internals/debugging/

This way, using different tools around the TF/Tofu ecosystem will be smoother without unecessary frictions.

Golang lib that can help:

- https://github.com/hashicorp/go-hclog

**Describe alternatives you've considered**

N/A.

**Additional context**

N/A.

**Comment by kvendingoldo** [comment]
@dvaumoron I think it's time to move to logger instead of prints :) WDYT?

**Comment by dvaumoron** [comment]
@kvendingoldo, the best would be a clear split between normal display and log, with maybe a way to disable even normal display

**Comment by samuel-phan** [comment]
Added https://github.com/hashicorp/go-hclog in case it can help.
