### ISSUE TITLE
tenv version command reporting "dev" instead of actual version

### ISSUE THREAD

**Issue by brainbug95** [tofuutils/tenv#42]
**Describe the bug**
I tried to implement an install or upgrade routine controlling the version of tenv installed or upgraded.

I discovered that both version commands `tenv --version` and `tenv version` report the string "dev" as the current version.

**To Reproduce**
execute `tenv --version` or `tenv version`

**Expected behavior**
Return the actually used version of the binary.

**Environment (please complete the following information):**
- OS: Debian 6.1.69-1 (2023-12-30) x86_64 GNU/Linux
- tfenv version 1.0.7

**Comment by dvaumoron** [comment]
As stated in https://github.com/tofuutils/tenv/blob/main/cmd/tenv/tenv.go#L38, the ldflags should override the value during a release build.

**Comment by kvendingoldo** [comment]
@dvaumoron i will check it

**Comment by kvendingoldo** [comment]
Fixed:
```
$ ./tenv  --version
tenv version v1.0.8
```
