### ISSUE TITLE
Add info about the selected TF/Tofu version when downloading one

### ISSUE THREAD

**Issue by samuel-phan** [tofuutils/tenv#43]
**Is your feature request related to a problem? Please describe.**

When running the proxy command `terraform`, if the TF/Tofu version is not available and needs to be downloaded, there is no output.

The download can take a while depending on the end-user bandwidth, and it's not user-friendly to display nothing.

I would expect also to have this additional info:

- From where `tenv` took the decision to download the given TF version (a `.terraform-version` file or env var, whatever).
- From where `tenv` fetches **all the releases info**. Previously we got this log:

  ```
  Fetching all releases information from https://artifactory.example.com/artifactory/hashicorp/terraform
  ```

- Any file that is downloaded in general (zip, SHASUMs, etc.)

**Describe the solution you'd like**

I would like to have a similar output as with [tfenv](https://github.com/tfutils/tfenv):

```
❯ terraform fmt
version '1.5.5' is not installed (set by /Users/sphan02/terraform/.terraform-version). Installing now as TFENV_AUTO_INSTALL==true
Installing Terraform v1.5.5
Downloading release tarball from https://artifactory.example.com/artifactory/hashicorp//terraform/1.5.5/terraform_1.5.5_darwin_arm64.zip
############################################################################################################################################################################ 100.0%
Downloading SHA hash file from https://artifactory.example.com/artifactory/hashicorp//terraform/1.5.5/terraform_1.5.5_SHA256SUMS
Not instructed to use Local PGP (/Users/sphan02/git/terraform/tfenv/use-{gpgv,gnupg}) & No keybase install found, skipping OpenPGP signature verification
Archive:  /var/folders/v5/8674lc4563d_n27g6998d0kc0000gn/T/tfenv_download.XXXXXX.s4JCoj7TiW/terraform_1.5.5_darwin_arm64.zip
  inflating: /Users/sphan02/git/terraform/tfenv/versions/1.5.5/terraform
Installation of terraform v1.5.5 successful. To make this your default version, run 'tfenv use 1.5.5'
```

**Describe alternatives you've considered**

```
❯ TFENV_VERBOSE=true terraform fmt
Failed to read terragrunt file : open terragrunt.hcl: no such file or directory
Failed to read terragrunt file : open terragrunt.hcl.json: no such file or directory
Scan project to find tf files
No compatible version found locally, search a remote one...
Can not read remote conf : open /Users/sphan02/.tenv/remote.yaml: no such file or directory
Fetching all releases information from https://artifactory.example.com/artifactory/hashicorp/terraform/index.json
Installation of Terraform 1.7.1
Fetching release information from https://artifactory.example.com/artifactory/hashicorp/terraform/v1.7.1/index.json
Failed to detect a version allowing to call terraform : unexpected value returned by API
```

**Additional context**

I understand that according to the strict definition of a proxy command, it shouldn't alter any behavior, but to me, user experience is more important, and I doubt that adding these outputs would dramatically prevent anyone using the TF output to be annoyed by these infos.

**Comment by dvaumoron** [comment]
I have added some message on the detection part during work on #40, a better splitting between print and log will be part of #41
