### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by kvendingoldo** [tofuutils/tenv#48]
- [x] Replace all TODO's to the required documentation.
- [x] Move sections inside of `version files` to `<details>`
- [x] Check all links in README.md
- [x] Add link to slack channel
- [x] Add examples about artifactory usage to README.md; Check them inside of https://github.com/tofuutils/tenv/issues/38
- [x] Check that all environment variables are described

**Comment by dvaumoron** [comment]
@astephanh, would you like to make a new PR in order to update README.md on atmos support you added ?

**Comment by astephanh** [comment]
> @astephanh, would you like to make a new PR in order to update README.md on atmos support you added ?

https://github.com/tofuutils/tenv/pull/131

**Comment by kvendingoldo** [comment]
cc https://github.com/MatthewJohn/terrareg/issues/42

**Comment by kvendingoldo** [comment]
https://github.com/tofuutils/tenv/pull/148
https://github.com/tofuutils/tenv/pull/147
https://github.com/tofuutils/tenv/pull/145
https://github.com/tofuutils/tenv/pull/144
https://github.com/tofuutils/tenv/pull/143
