### ISSUE TITLE
Add chocolatey support

### ISSUE THREAD

**Issue by kvendingoldo** [tofuutils/tenv#55]
We need to add a support of installing tenv from choco.
https://goreleaser.com/customization/chocolatey/

**Comment by tedivm** [comment]
I'm writing a book on Terraform ([Terraform in Depth](https://www.manning.com/books/terraform-in-depth)) and am discussing `tenv` in the chapter I'm currently writing. I just wanted to ask what the timeframe work chocolately support is, as I want to include installation instructions for both macos and windows users.

**Comment by kvendingoldo** [comment]
@tedivm thank you for  your interest in tenv. We gonna finish the work on MSI/choco packages till end of this week.

**Comment by cgagnon-crakmn** [comment]
The choco support is really interesting. On what exactly do you need help @kvendingoldo? I work with a team that uses WSL and Windows and we really need to manage terraform versions on Windows easily.

**Comment by kvendingoldo** [comment]
By default, goreleaser can't create choco package, only exe and we do that. I don't have any windows machine and still thinking how we can automate choco package building. Looks like that we can start from manual build on a windows machine. You can help us and build choco package at your Windows machine, or I will find a Windows VM and build tenv choco package.

**Comment by tedivm** [comment]
Can I get an update on this? If it's not going to be done I want to make sure I *don't* include the choco install instructions in my book. I'll still include tenv, but it would definitely be easier for windows teams if Choco was an option for them. If not that then at least some readme instructions for windows users.

**Comment by kvendingoldo** [comment]
@tedivm Added info about choco installation to README.md

**Comment by tedivm** [comment]
This is awesome, thank you!

**Comment by SamKompfner-Liberis** [comment]
when will the package actually appear in Chocolatey? Currently installation steps for Choco are not working as the package doesn't exist

**Comment by kvendingoldo** [comment]
@SamKompfner-Liberis I see that it's stuck on 

```
Scan Testing Resulted in Flagged as a Note:
At least one file within this package has greater than 0 detections, but less than 5
```

stage. Do you probably know how to speed up the approve?

**Comment by SamKompfner-Liberis** [comment]
https://community.chocolatey.org/packages/tenv/1.7.0

I'm afraid not.

**Comment by kvendingoldo** [comment]
@SamKompfner-Liberis @tedivm @cgagnon-crakmn the choco package has finally approved! If you have any issues, raise a new issue, please.

**Comment by SamKompfner-Liberis** [comment]
good stuff, thank you!

**Comment by tedivm** [comment]
Thanks so much! You'll be super happy to know it's already in Chapter 7 of my book, and I also mentioned tenv in chapter 8 for the Terragrunt support. I love that we have one tool that does it all.

**Comment by kvendingoldo** [comment]
@tedivm wow! great, thanks a lot! :)
