### ISSUE TITLE
Failed to detect a version allowing to call terraform

### ISSUE THREAD

**Issue by maxwelllwang** [tofuutils/tenv#65]
**Describe the bug**
tenv doesn't install terraform versions < 1.2.0

tried this on several version doesn't work on anything less than 1.2.0

**To Reproduce**
1. set `.terraform-version` to `0.15.0`
2. run `terraform init`

**Expected behavior**
downloads and uses terraform version 0.15.0

**Screenshots**
```
Resolved version from .terraform-version : 0.15.0
Installing Terraform 0.15.0
Fetching release information from https://releases.hashicorp.com/terraform/0.15.0/index.json
Failed to detect a version allowing to call terraform : searched asset not found
```

**Environment (please complete the following information):**
- OS: macos m1
- tenv version v1.0.15

**Additional context**

**Comment by maxwelllwang** [comment]
I think this is due to the fact that < 1.2 doesn't have arm binaries. I wonder how I could use tfenv to install it though.

**Comment by kvendingoldo** [comment]
By default, it will use the same arch, as tenv. Do you need that it's useful?

**Comment by dvaumoron** [comment]
An architecture override will install binaries which will not work on the current system, i do not see that as an useful feature.

**Comment by dvaumoron** [comment]
Ok, after a check, there is compatibility option with Rosetta.

So it would be better to add ways to override the default arch.

**Comment by dvaumoron** [comment]
The PR add TENV_ARCH, (and equivalent TOFUENV_ARCH and TFENV_ARCH) and a `--a`, `--arch` flag to override the current tenv binaries arch
