### ISSUE TITLE
`tenv` managed terraform causes illegal characters for `terraform output -json`

### ISSUE THREAD

**Issue by svivekkrishna** [tofuutils/tenv#66]
**Describe the bug**

When the terraform version is managed with `tenv, it is adding a `Resolved version from ...` message at the beginning of the output. This causes JSON (or any structured terraform output) to have illegal characters in it.

**To Reproduce**
1. Install a version of terraform with `tenv tf install 1.5.0` (or any other version).
2. Run `terraform apply`
3. Run `terraform output -no-color -json`
4. See error in the output

```bash
❯ terraform output -no-color -json
Resolved version from /Users/<user_name>/.tenv/Terraform/version : 1.5.0
{
  "test_output": "Hello world!"
}
```

**Expected behavior**
tenv shouldn't be prefixing the terraform resolution message: `Resolved version from /<user_home>/.tenv/Terraform/version : 1.5.0` or should at least have a documented way to suppress this warning.

**Screenshots**

**Environment (please complete the following information):**
- OS: MacOS Catalina
- tofuenv version v1.0.15

**Additional context**

This error doesn't occur with `tfenv`.

**Comment by dvaumoron** [comment]
There is a documented way to suppress informative display : TENV_QUIET=true

Also, as stated in #63 , i will probably change to redirect all informative display to stderr
