### ISSUE TITLE
Feature request: add terraform vs tofu agnostic command

### ISSUE THREAD

**Issue by stephan242** [tofuutils/tenv#73]
**Is your feature request related to a problem? Please describe.**
We're transitioning from using terraform to using tofu. Now some directories are managed by terraform, and will be for the foreseeable future, while others are already managed by tofu. This produces 2 problems for me:

- My [grugbrain](https://grugbrain.dev/) can'tr cope with this. I type `tofu` when I should type `terraform` and vice versa.
- My [vim-terraform](https://github.com/hashivim/vim-terraform/blob/master/doc/terraform.txt) plugin always types `terraform` as per the default. There's a config option to change this, called `g:terraform_binary_path`. I guess other editors work similarly.

**Describe the solution you'd like**
I would like to see a command, installed by tenv, which I can use in either of these directories, which will automatically either run tofu or terraform for me, based on what `tenv detect` detects to be needed locally.

**Describe alternatives you've considered**
For my brain I don't see much hope. For vim, I guess I could learn lua and botch something together that essentially repeats what `tenv detect` does, based on the files it finds, and then configures vim-terraform dynamically. But that would be very hacky. Plus I guess other editors might benefit from such a proposed binary as well, so seems to me the better place to fix this within `tenv`.

**Additional context**
Just as a suggestion for a name for this binary: `tf` which seems to be the common denominator out of TerraForm and ToFu. But I don't mind, any name will do for me.

**Comment by dvaumoron** [comment]
If i understand your need, you want a `tf` command which redirect on `tofu` if there is a `.opentofu-version` and on `terraform` if there is a `.terraform-version` (or equivalent `.tfswitchrc`) ?

**Comment by yermulnik** [comment]
After spending half an hour figuring how to get rid of ambiguous `tf` binary on the `PATH`, I'm wondering why there's no `t` binary installed by `tenv`, as I have lots of colleagues who aliased `terraform` to `t` rather than to `tf` 🤦🏻
