### ISSUE TITLE
Cosign test is faling

### ISSUE THREAD

**Issue by kvendingoldo** [tofuutils/tenv#75]
**Describe the bug**
https://github.com/tofuutils/tenv/actions/runs/7963038025/job/21737807413

**Comment by dvaumoron** [comment]
I fixed the test locally, but i still have an error when launching it from another folder... I continue to work on it...

**Comment by dvaumoron** [comment]
Ok, the weird behavior was caused by `t.Parallel()`. I removed it in all cosign tests, and now they seem to work as expected.

**Comment by kvendingoldo** [comment]
Nice!
