### ISSUE TITLE
Erase big file from git history

### ISSUE THREAD

**Issue by dvaumoron** [tofuutils/tenv#76]
**Is your feature request related to a problem? Please describe.**
Reduce the project size in order to make it easier to clone.

**Describe the solution you'd like**
Can erase (not used anymore) :
- pkg/check/cosign/tofu_1.6.0_arm64.deb 
- pkg/check/sha256/testdata/tofu_1.6.0_linux_arm64.zip

**Describe alternatives you've considered**
None

**Additional context**
tools like git-filter-repo allow to do that easily 

Unsure about the effect on existing tag

**Comment by kvendingoldo** [comment]
I will able to do it EOF if you want.

**Comment by dvaumoron** [comment]
@kvendingoldo, branchs still contains the "erased" files, I delete my merged branchs, but you work on https://github.com/tofuutils/tenv/tree/feat/add-aur-deployment which is not merged yet.

However, it seem that only .goreleaser.yaml have changed, can i recreate the branch based on the current main ? Or is there other change to include ?

**Comment by kvendingoldo** [comment]
@dvaumoron sure, go ahead. I will return to AUR deployment later, no worries about these changes

**Comment by dvaumoron** [comment]
I recreated the branch "feat/add-aur-deployment", however that did not work, a fresh clone still contains in its history the deleted files. I think that without erasing all previous tag, we can not get rid of them (recreating the history again clean the local part, but a new force push does not impact github copy).
