### ISSUE TITLE
Replace external tofuenv to a native Go support 

### ISSUE THREAD

**Issue by kvendingoldo** [tofuutils/tenv#8]

**Comment by dvaumoron** [comment]
Hi @kvendingoldo,

Just seen you create this issue to continue our exchange started in https://github.com/tofuutils/tofuenv/issues/31

**Comment by kvendingoldo** [comment]
@dvaumoron yep. Today's I gonna upload basic layout to `main` branch. It can help us to see how we can merge our code. I will additionally ping you when it will be done.

**Comment by kvendingoldo** [comment]
@dvaumoron I've added a basic layout for `tenv` commands. Don't see to `pkg` code, it's unused for now. I appreciate your work and think that it won't be a problem to integrate it into `tenv tf` command. If you are ok with that, I will add you to the repo as a maintainer. Let's make this tool better together.

**Comment by kvendingoldo** [comment]
@dvaumoron wdyt?

**Comment by dvaumoron** [comment]
I am first working on adding Terraform support to gotofuenv, the progress are fast.

After that (probably during next week), an eventual reorganization of commands  will be easier.

**Comment by kvendingoldo** [comment]
@dvaumoron that sounds fantastic! Are you planning to merge your code with tenv after that? For the time being, I notice that we are doing nearly identical job, which is inefficient in my opinion.

**Comment by dvaumoron** [comment]
The refactor with a ReleaseInfoRetriever interface will allow a better reusability of the code (if we want to keep same kind of functionnality for OpenTofu and Terraform)

I don't understand why you call it inefficiency, my work is not hidden, its location of availability doesn't change much.

**Comment by dvaumoron** [comment]
Hi @kvendingoldo,

I released gotofuenv v1.0.0, I will slow down on it for now (only fix bugs if needed).

Before going further, I wonder, what do you envision for tenv ? What do you think should be done differently ?

**Comment by kvendingoldo** [comment]
Hello @dvaumoron! I wanted to express my admiration for your incredible work. 

In my previous comment, I was talking about my team's work as about smth not very useful because your code looks almost the same as we realized. Please accept my apologies for any unintended negative tone, and I genuinely commend your outstanding contribution to the migration of tofu/tf env to Golang.

We was waiting news from your side and for this reason we stopped tenv development for a while. My team still want to keep the original idea of this united tool inside of tofuutils organization and develop / promote and enchace it together in the future.

What's your thougts about the future of tool that you have written? Don't you want to migrate it to the tofuutils organisation and be a primary maintainer of it?

**Comment by dvaumoron** [comment]
As said on Slack, I am ready to migrate, but when trying to transfer that did not work yet ("You don’t have the permission to create public repositories on tofuutils").

**Comment by kvendingoldo** [comment]
@dvaumoron can you check it now, please? I sent you an invitation. 
btw. WDYT about renaming your tool to tenv? I think this name will be more suitable. We can do it after transfer.

**Comment by dvaumoron** [comment]
I started to update after the transfer to tofuutils, I launched a release, the brew part failed.

**Comment by kvendingoldo** [comment]
@dvaumoron pls, check again. I fixed permissions

**Comment by dvaumoron** [comment]
Everything seem to work as expected now (including the brew migration part in dvaumoron/tap, not sure there is a lot of users concerned except me, but that still better).

I followed your suggestion and renamed the managing command `tenv` (I tried to update display and README Accordingly, but there are still some mistake, however I will wait more important fixes before releasing again).

**Comment by kvendingoldo** [comment]
@dvaumoron I merged your repo to `tenv` and saved all history that you had: https://github.com/tofuutils/tenv
Don't you have any objections to use tenv for the future?

**Comment by dvaumoron** [comment]
I have no objection, however i have some questions. Now, my work has been merge in the tenv repo, it seems appropriate to indicate in the gotofuenv readme that the work will continue there, mark it as archived, and use the formula_renames.json mecanism from brew. Do you agree ?

**Comment by kvendingoldo** [comment]
@dvaumoron yep, I absolutely agree with you. I can do it today, or you can do it by yourself. Also, I will add the information to tofuenv readme.

**Comment by dvaumoron** [comment]
Updated the readme and added formula_renames.json, however i can not change gotofuenv repository in an archived one, I will let you do it.

**Comment by kvendingoldo** [comment]
@dvaumoron I think that it's time to close this issue :) Great work!

**Comment by kvendingoldo** [comment]
Done by @dvaumoron
