### ISSUE TITLE
Request: Allow `terraform` as a human-friendly alias for `tf` tool

### ISSUE THREAD

**Issue by RDhar** [tofuutils/tenv#92]
**Is your feature request related to a problem? Please describe.**

Not a problem as much as just a wee bit of ambiguity.

As I'm moving between Tofu and Terraform frequently (for testing compatibility, migrations paths, and the likes), I've come to appreciate explicit distinction when referencing both tools in various workflows, [often simultaneously](https://github.com/DevSecTop/TF-via-PR-Comments/pull/193/files).

**Describe the solution you'd like**

As a result, it'd be splendid if `tenv` would support aliases for the tool names.

While this request is specifically to allow `terraform` as an alias for `tf`, I'm equally fond of adding human-friendly aliases for the others as well. For example:

| tool                     | env vars                   | description                                    |
| ------------------------ | -------------------------- | ---------------------------------------------- |
| `tofu` (or `opentofu`)   | [TOFUENV_](#tofu-env-vars) | [OpenTofu](https://opentofu.org)               |
| `tf`   (or `terraform`)  | [TFENV_](#tf-env-vars)     | [Terraform](https://www.terraform.io/)         |
| `tg`   (or `terragrunt`) | [TG_](#tg-env-vars)        | [Terragrunt](https://terragrunt.gruntwork.io/) |

**Describe alternatives you've considered**

The simple workaround is to just use the specified tool name, adapting it as and when required. That being said, I believe this would be a nice-to-have feature that would make the tool more user-friendly.

**Additional context**

Big thanks to @kvendingoldo for [identifying](https://github.com/DevSecTop/TF-via-PR-Comments/issues/140#issuecomment-2034382785) `tenv` as a good fit for [DevSecTop/TF-via-PR-Comments](https://github.com/DevSecTop/TF-via-PR-Comments) GH Action workflow!

**Comment by kvendingoldo** [comment]
I think it's not a problem to create an alias. @dvaumoron as I understand correctly, we just need to add additional binaries like terraform.go or tofu.go, yep?

**Comment by dvaumoron** [comment]
> I think it's not a problem to create an alias. @dvaumoron as I understand correctly, we just need to add additional binaries like terraform.go or tofu.go, yep?

That seem strange to me, why create copies of the binaries ? They would be exactly the sames, why a shell alias doesn't work ?

**Comment by RDhar** [comment]
Hey @dvaumoron, you're absolutely right in that `terraform` is more letters to type than `tf`. With that said, this request is for additional alias(es) only, which would be available for use on top of the existing `tf` option, not instead of it. 

As for why a longer name would be preferred, that's a fair ask. 

To share more context, I tend to provision OpenTofu/Terraform via CI automation like GitHub Actions. And when I see a line like `tenv tf install latest`, it's not immediately obvious to me which tool it's in reference to. Especially now, when frequently moving/testing between OTF and TF -- all the while using `.tf` files -- I think we can agree there's a wee bit of ambiguity here. 

And that's not getting into the inconsistency of tool/proxy naming. For example, one would `tofu init` so `tenv tofu install latest` makes total sense as a 1:1 match. Whereas, it's `terraform init` so `tenv tf install latest` has me pausing for a moment to check that correlates with the correct tool. 

Though I was hoping there might be a more shell-oriented route for managing aliases. I have to agree that spinning off whole entire additional binaries just to support aliases seems like a heavy solution. Though I don't have a better one to offer in its place.

**Comment by dvaumoron** [comment]
Ok, I get it. It is easy to add sub command aliases in `tenv` command (the project does not use separate binaries for that, as I said, the other binaries are proxy to the managed tools).

**Comment by RDhar** [comment]
Many thanks on such a swift turnaround, and even going beyond the request! 🙌

**Comment by dvaumoron** [comment]
@RDhar, I forgot to mention that once **tenv** installed, a `terraform init` is enough (the proxy is able to download a version if there is none, the default strategy will be `latest-allowed` when there is no `.terraform-version` file)

**Comment by RDhar** [comment]
Nice one, that's convenient! 

Although, the default `ubuntu-latest` GH Action runner [ships with its own software](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#:~:text=SVN%201.14.1-,Terraform%201.7.5,-yamllint%201.35.1), including Terraform, which means `tenv` gets ignored unless explicitly called first. 🫤

Down the line, Terraform might be phased out of open-source default packages, as we see with: [GitLab](https://gitlab.com/components/opentofu#migrating-from-the-terraform-cicd-templates), [Brew](https://formulae.brew.sh/formula/terraform) and [Alpine Linux](https://gitlab.alpinelinux.org/alpine/aports/-/issues/15193). In which case, `tenv` becomes even more valuable!

**Comment by RDhar** [comment]
Ah, as it happens, `tenv` being over-riden by GH Action runner's default `terraform` binary just became a problem in #93. Despite installing/using a specific version of Terraform, the runner's in-built binary is used instead, as [demonstrated here](https://github.com/DevSecTop/TF-via-PR-Comments/actions/runs/8572655810/job/23495699988#step:3:49):

```sh
$ tenv terraform use 1.6.1
$ terraform --version
...
Installation of Terraform 1.6.1 successful
Written 1.6.1 in /home/runner/.tenv/Terraform/version
Terraform v1.7.5
on linux_amd64
```
