### ISSUE TITLE
Request: Export `stdout`, `stderr`, and `exitcode` equivalent outputs

### ISSUE THREAD

**Issue by RDhar** [tofuutils/tenv#93]
> **Is your feature request related to a problem? Please describe.**

Not a problem, just curious if a certain feature parity could be matched with the likes of [setup-opentofu](https://github.com/opentofu/setup-opentofu) or [setup-terraform](https://github.com/hashicorp/setup-terraform) GH Actions. 

Both of these GH Action ship with their own wrapper script which exposes `stdout`, `stderr`, and `exitcode` automatically by default. These outputs can be leveraged in subsequent steps, for example, to reproduce the proposed plan and/or fmt diff in a [PR comment like so](https://github.com/DevSecTop/TF-via-PR-Comments/pull/193#issuecomment-2034874392).

Is there a similar-ish equivalent for sourcing tenv outputs?

---

> **Describe the solution you'd like**

I can imagine this is a "deceptively simple" request. The aforementioned setup-opentofu/terraform Actions are... Actions. Naturally, it's easier for them to supply a wrapper script with custom outputs which are particularly suited for use in CI automation. 

---

> **Describe alternatives you've considered**

While I've just used setup-opentofu/terraform directly with their wrappers enabled, I'm just as open to workaround suggestions using bash/shell within CI context.

---

> **Additional context**

Thanks to @kvendingoldo for [identifying](https://github.com/DevSecTop/TF-via-PR-Comments/issues/140#issuecomment-2034382785) `tenv` as a good fit for [DevSecTop/TF-via-PR-Comments](https://github.com/DevSecTop/TF-via-PR-Comments/pull/193/files), where I'm keen to use `tenv` in a scenario which tests both `terraform` and `tofu` execution simultaneously.

**Comment by dvaumoron** [comment]
Hi @RDhar,

I dug into the GitHub Actions documentation in order to understand what could be done...

I think it is doable to add an environment variable recognized by **tenv** proxies to activate a "GitHub Actions mode" where GITHUB_OUTPUT is taken in account.

**Comment by dvaumoron** [comment]
I wonder why you group in one line :

`tenv ${TENV_TOOL} install latest && ${CLI_USES} --version`

instead of :

```
tenv ${TENV_TOOL} install latest
${CLI_USES} --version
```

?

**Comment by dvaumoron** [comment]
The output written in GITHUB_OUTPUT file should follow https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-of-a-multiline-string

**Comment by RDhar** [comment]
Hi @dvaumoron, thank you for taking time out to look into this request already! 

---

> I think it is doable to add an environment variable recognized by tenv proxies to activate a "GitHub Actions mode"...

I was poking around the docs and found a set of [default environment variables](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables) present in each step of every workflow. Most notably are `CI` and `GITHUB_ACTIONS` which are always set to `true`, particularly the latter only being `true` when it's being run by GH Action.

---

> I wonder why you group in one line...

Absolutely no good reason whatsoever; maybe just to group the TF-related commands altogether? It's separated out now with 1 fewer variable, [thanks to you](https://github.com/DevSecTop/TF-via-PR-Comments/pull/193/files)! 

Though I was curious to ask: does installing the 2 packages like `sudo dpkg -i "cosign..." "tenv..."` ensure that cosign is used when required by tenv automatically?

---

> The output written in GITHUB_OUTPUT file should follow...

While the officially documented method is one approach to storing multiline strings in `GITHUB_OUTPUT` variables:

```shell
run: |
  {
    echo 'JSON_RESPONSE<<EOF'
    curl https://example.com
    echo EOF
  } >> "$GITHUB_OUTPUT"
```

I wanted to share a working alternative as well, which is not better by any means, just another option that's available:

```shell
run: |
  echo 'JSON_RESPONSE<<EOF' >> $GITHUB_OUTPUT
  curl https://example.com
  echo EOF >> $GITHUB_OUTPUT
```

**Comment by dvaumoron** [comment]
> Most notably are `CI` and `GITHUB_ACTIONS` which are always set to `true`, particularly the latter only being `true` when it's being run by GH Action.

Ok, I will probably check `GITHUB_ACTIONS` to detect this use case.

> Though I was curious to ask: does installing the 2 packages like `sudo dpkg -i "cosign..." "tenv..."` ensure that cosign is used when required by tenv automatically?

**tenv** use [Command](https://pkg.go.dev/os/exec#Command) from "os/exec" in go standard library, which check the path to find `cosign`, so I think it should work fine.

> While the officially documented method is one approach to storing multiline strings in `GITHUB_OUTPUT` variables

As guessable from the previous answer, **tenv** project do not use shell script, but compiled binaries written using the go language. So I will write some go code to do the task :wink:

**Comment by RDhar** [comment]
There's _no way_ you implemented multi-line string output for GH Action workflow steps specifically, this fast! 🤯

Is there anyway to test this before your next release by amending the usual `curl` command?

```sh
curl https://api.github.com/repos/tofuutils/tenv/releases/latest | jq -r .tag_name
```

**Comment by dvaumoron** [comment]
I released 1.6.0

**Comment by RDhar** [comment]
That's fantastic, thank you! 

As [tested on this PR](https://github.com/DevSecTop/TF-via-PR-Comments/pull/193#issuecomment-2040141171), we can confirm that `tofu` via `tenv` outputs are parsed _exactly_ in the exact same way as [setup-opentofu](https://github.com/opentofu/setup-opentofu) (with its wrapper-script enabled (by default)).

![image](https://github.com/tofuutils/tenv/assets/19497993/e3114064-b4e5-4766-a7bc-ab2d9ff9cae8)

**Comment by RDhar** [comment]
However, I'm running into a problem with Terraform which I'm hoping could be simple fix or command misunderstanding. 

Despite [explicitly installing & using](https://github.com/DevSecTop/TF-via-PR-Comments/pull/193/files) the latest `terraform` via `tenv`, it seems as if the [GH Action runner's default/in-built Terraform binary](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#:~:text=SVN%201.14.1-,Terraform%201.7.5,-yamllint%201.35.1) is overriding `tenv`. 

This is proven by the [workflow log](https://github.com/DevSecTop/TF-via-PR-Comments/actions/runs/8572655810/job/23495699988#step:3:49):

```sh
$ tenv ${CLI_USES} use 1.6.1
$ ${CLI_USES} --version
...
Installation of Terraform 1.6.1 successful
Written 1.6.1 in /home/runner/.tenv/Terraform/version
Terraform v1.7.5
on linux_amd64
```

As a result, Terraform fails to return any expected outputs as `tenv` is being ignored altogether 🫤

**Comment by RDhar** [comment]
Just to confirm altogether, @dvaumoron, would you give this your seal of approval for "recommended" steps in order to install/use a given `tenv` proxy within GH Actions context?

```sh,
- name: Setup TF (via tenv)
  run: |
    LATEST_COSIGN=$(curl --silent https://api.github.com/repos/sigstore/cosign/releases/latest | jq -r .tag_name | tr -d "v")
    curl -O -L "https://github.com/sigstore/cosign/releases/latest/download/cosign_${LATEST_COSIGN}_amd64.deb"
    LATEST_TENV=$(curl --silent https://api.github.com/repos/tofuutils/tenv/releases/latest | jq -r .tag_name)
    curl -O -L "https://github.com/tofuutils/tenv/releases/latest/download/tenv_${LATEST_TENV}_amd64.deb"
    sudo dpkg -i "cosign_${LATEST_COSIGN}_amd64.deb" "tenv_${LATEST_TENV}_amd64.deb"
    tenv terraform use 1.6.1 && tenv update-path
```

I can [confirm the above works](https://github.com/DevSecTop/TF-via-PR-Comments/pull/193/files) exactly as intended, but I'm just looking for confirmation on whether I'm following all of the best-practices or missing any other tips.

**Comment by dvaumoron** [comment]
As stated (https://github.com/tofuutils/tenv/issues/98#issuecomment-2041002206), I would have used `tenv terraform constraint "<= 1.5.7"`.

The choice of `constraint` allows project to rely on `latest-allowed` detection (but still use an open source version) or specify their own settings (the retarded installation with display doesn't matter here, the proxy display is not part of the exposed data).

**Comment by dvaumoron** [comment]
Moreover, the cosign part is needed in OpenTofu case but not in Terraform case (Hashicorp only use PGP signature).
